abstract: "Get the home directory for yourself or other users\r"
author: "Adam Kennedy <cpan@ali.as>\r"
build_requires:
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.50
license: perl
name: File-HomeDir
no_index:
  directory:
    - inc
    - t
requires:
  File::Spec: 0.80
  perl: 5.005
version: 0.52
