---
abstract: 'Find your home and other directories, on any platform'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: File::HomeDir
name: File-HomeDir
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Cwd: 3.12
  File::Spec: 3.12
  perl: 5.00503
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/File-HomeDir
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/File-HomeDir
version: 0.89
