
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.63
distribution_type: module
version: 0.60_01
name: File-HomeDir
author: Adam Kennedy <cpan@ali.as>
license: perl
build_requires: 
  Test::More: 0.47
  English: 0
requires: 
  perl: 5.005
  File::Spec: 0.80
abstract: Get the home directory for yourself or other users
