---
abstract: 'Find your home and other directories, on any platform'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.48
distribution_type: module
generated_by: 'Module::Install version 0.81'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: File::HomeDir
name: File-HomeDir
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Cwd: 3.12
  File::Spec: 3.12
  perl: 5.00503
resources:
  license: http://dev.perl.org/licenses/
version: 0.86
