name: File-HomeDir
version: 0.07
abstract: Get the home directory for ourself and other users
author: Adam Kennedy <cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  Test::More: 0.47
requires:
  perl: 5.004
  File::Spec: 0.80
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.37
